-- 코드를 작성해주세요
SELECT ED.ID as ID, 
CASE 
WHEN ED.r = 1 THEN 'CRITICAL'
WHEN ED.r = 2 THEN 'HIGH'
WHEN ED.r = 3 THEN 'MEDIUM'
ELSE 'LOW' END AS COLONY_NAME
FROM (
    SELECT ID, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) as r
    FROM ECOLI_DATA
) ED
ORDER BY ED.ID ASC