-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, CONCAT_WS(" ", CITY, STREET_ADDRESS1, STREET_ADDRESS2)AS 전체주소, CONCAT_WS("-", SUBSTRING(TLNO, 1, 3), SUBSTRING(TLNO, 4, 4), SUBSTRING(TLNO, 8, 4))AS 전화번호
FROM USED_GOODS_BOARD UB LEFT JOIN USED_GOODS_USER UR
ON UB.WRITER_ID = UR.USER_ID
GROUP BY UR.USER_ID
HAVING COUNT(UB.CREATED_DATE) >= 3
ORDER BY UR.USER_ID DESC;
