-- 코드를 입력하세요
SELECT RI.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM REST_INFO RI JOIN (
    SELECT ROUND(AVG(REVIEW_SCORE), 2) as SCORE, REST_ID
    FROM REST_REVIEW
    GROUP BY REST_ID) AS RV
ON RI.REST_ID = RV.REST_ID
where ADDRESS like '서울%'
ORDER BY SCORE DESC, FAVORITES DESC