-- 코드를 입력하세요
SELECT FP.PRODUCT_ID as PRODUCT_ID, FP.PRODUCT_NAME as PRODUCT_NAME, FP.PRICE * FO.AMOUNT as TOTAL_SALES
FROM FOOD_PRODUCT FP JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) as AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE >= '2022-05-01' AND PRODUCE_DATE < '2022-06-01'
    GROUP BY PRODUCT_ID
) as FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
