-- 코드를 입력하세요
SELECT E.APNT_NO AS APNT_NO, P.PT_NAME AS PT_NAME, E.PT_NO AS PT_NO, E.MCDP_CD AS MCDP_CD, E.name AS DR_NAME, E.APNT_YMD AS APNT_YMD
FROM PATIENT P JOIN (
    SELECT A.APNT_NO, A.PT_NO, A.MCDP_CD, D.DR_NAME as name, A.APNT_YMD
    FROM APPOINTMENT A JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
    WHERE A.MCDP_CD = 'CS' AND A.APNT_CNCL_YN = 'N' AND A.APNT_YMD BETWEEN DATE('2022-04-13') AND DATE('2022-04-14')
) as E
ON P.PT_NO = E.PT_NO
ORDER BY APNT_YMD