-- 코드를 입력하세요
SELECT UR.USER_ID, UR.NICKNAME, SUM(UB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS UB LEFT JOIN USED_GOODS_USER AS UR
ON UB.WRITER_ID = UR.USER_ID
WHERE UB.STATUS = "DONE"
GROUP BY UR.USER_ID, UR.NICKNAME
HAVING SUM(UB.PRICE) >= 700000
ORDER BY SUM(UB.PRICE) ASC;