-- 코드를 입력하세요
SELECT CATEGORY, COUNT(PRODUCTS) FROM (
    SELECT SUBSTRING(PRODUCT_CODE,1, 2) AS CATEGORY, COUNT(PRODUCT_ID) AS PRODUCTS 
    FROM PRODUCT
    GROUP BY PRODUCT_CODE
    ) as A
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;    