-- 코드를 입력하세요
SELECT DISTINCT car.CAR_ID AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR car LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY his
ON car.CAR_ID = his.CAR_ID
WHERE his.CAR_ID is NOT NULL AND car.CAR_TYPE = "세단" AND his.START_DATE LIKE "2022-10%"
ORDER BY car.CAR_ID DESC;
