-- 코드를 작성해주세요
SELECT FISH_INFO.ID, a.FISH_NAME, a.LENGTH
FROM (
    SELECT A.FISH_TYPE, FISH_NAME_INFO.FISH_NAME, A.LENGTH
    FROM (
        SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH FROM FISH_INFO GROUP BY FISH_TYPE
    ) AS A LEFT JOIN FISH_NAME_INFO
    ON A.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
      ) AS a LEFT JOIN FISH_INFO
ON a.FISH_TYPE = FISH_INFO.FISH_TYPE
WHERE FISH_INFO.LENGTH = a.LENGTH
ORDER BY FISH_INFO.ID ASC
;


