-- 코드를 작성해주세요
SELECT SUM(H.SCORE) AS SCORE, H.EMP_NO, T.EMP_NAME, T.POSITION, T.EMAIL
FROM HR_GRADE H JOIN (SELECT E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL 
            FROM HR_DEPARTMENT D JOIN HR_EMPLOYEES E
            ON D.DEPT_ID = E.DEPT_ID
           ) AS T
ON H.EMP_NO = T.EMP_NO
GROUP BY H.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;
