SELECT A.CATEGORY, SUM(B.sale) AS TOTAL_SALES
FROM BOOK A 
JOIN (SELECT SUM(SALES) as sale, book_id
from BOOK_SALES 
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY book_id) B
ON A.book_id = B.book_id
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY