SELECT B.CATEGORY, SUM(S.SALES) as TOTAL_SALES
FROM BOOK B JOIN (
    SELECT BOOK_ID, SUM(SALES) as SALES
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN DATE('2022-01-01') AND DATE('2022-01-31')
    GROUP BY BOOK_ID
                  
) as S
ON B.BOOK_ID = S.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY