-- 코드를 입력하세요
SELECT BK.CATEGORY, SUM(bs.SALES) AS TOTAL_SALES 
FROM BOOK AS BK LEFT JOIN BOOK_SALES AS BS
ON BK.BOOK_ID = BS.BOOK_ID
WHERE BS.BOOK_ID is NOT NULL AND BS.SALES_DATE LIKE "2022-01%"
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;

# SELECT BOOK_ID, SUM(SALES) 
# FROM BOOK_SALES
# WHERE SALES_DATE LIKE "2022-01%"
# GROUP BY BOOK_ID;