-- 카테고리별 최대 가격을 구한 뒤 그 가격과 일치하는 행만 조인
SELECT A.CATEGORY, A.PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT AS A
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
    GROUP BY CATEGORY
) AS M
  ON A.CATEGORY = M.CATEGORY
 AND A.PRICE    = M.MAX_PRICE
WHERE A.CATEGORY IN ('과자','국','김치','식용유')
ORDER BY A.PRICE DESC, A.PRODUCT_NAME ASC;