SELECT COUNT(LE.ID)AS FISH_COUNT, MAX(LE.LENGTH) AS MAX_LENGTH, LE.FISH_TYPE AS FISH_TYPE
FROM FISH_INFO F RIGHT JOIN (SELECT ID, FISH_TYPE, IFNULL(LENGTH, 10) AS LENGTH
                     FROM FISH_INFO
                    ) LE
ON F.ID = LE.ID
GROUP BY LE.FISH_TYPE
HAVING AVG(LE.LENGTH) >= 33
ORDER BY LE.FISH_TYPE ASC;